
package com.jyd.message;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISendMessage", targetNamespace = "http://message.jyd.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISendMessage {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllClientUser", targetNamespace = "http://message.jyd.com/", className = "com.jyd.message.GetAllClientUser")
    @ResponseWrapper(localName = "getAllClientUserResponse", targetNamespace = "http://message.jyd.com/", className = "com.jyd.message.GetAllClientUserResponse")
    public List<Integer> getAllClientUser();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendMessageToAllClient", targetNamespace = "http://message.jyd.com/", className = "com.jyd.message.SendMessageToAllClient")
    @ResponseWrapper(localName = "sendMessageToAllClientResponse", targetNamespace = "http://message.jyd.com/", className = "com.jyd.message.SendMessageToAllClientResponse")
    public void sendMessageToAllClient(
        @WebParam(name = "arg0", targetNamespace = "")
        ServerMessage arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendMessageToClient", targetNamespace = "http://message.jyd.com/", className = "com.jyd.message.SendMessageToClient")
    @ResponseWrapper(localName = "sendMessageToClientResponse", targetNamespace = "http://message.jyd.com/", className = "com.jyd.message.SendMessageToClientResponse")
    public void sendMessageToClient(
        @WebParam(name = "arg0", targetNamespace = "")
        ServerMessage arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
