
package com.jyd.message;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SendMessageService", targetNamespace = "http://message.jyd.com/", wsdlLocation = "http://localhost:9080/MessageSender/webservice/sendMessage?wsdl")
public class SendMessageService
    extends Service
{

    private final static URL SENDMESSAGESERVICE_WSDL_LOCATION;
    private final static WebServiceException SENDMESSAGESERVICE_EXCEPTION;
    private final static QName SENDMESSAGESERVICE_QNAME = new QName("http://message.jyd.com/", "SendMessageService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/MessageSender/webservice/sendMessage?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDMESSAGESERVICE_WSDL_LOCATION = url;
        SENDMESSAGESERVICE_EXCEPTION = e;
    }

    public SendMessageService() {
        super(__getWsdlLocation(), SENDMESSAGESERVICE_QNAME);
    }

    public SendMessageService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDMESSAGESERVICE_QNAME, features);
    }

    public SendMessageService(URL wsdlLocation) {
        super(wsdlLocation, SENDMESSAGESERVICE_QNAME);
    }

    public SendMessageService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDMESSAGESERVICE_QNAME, features);
    }

    public SendMessageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendMessageService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISendMessage
     */
    @WebEndpoint(name = "SendMessagePort")
    public ISendMessage getSendMessagePort() {
        return super.getPort(new QName("http://message.jyd.com/", "SendMessagePort"), ISendMessage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISendMessage
     */
    @WebEndpoint(name = "SendMessagePort")
    public ISendMessage getSendMessagePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://message.jyd.com/", "SendMessagePort"), ISendMessage.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDMESSAGESERVICE_EXCEPTION!= null) {
            throw SENDMESSAGESERVICE_EXCEPTION;
        }
        return SENDMESSAGESERVICE_WSDL_LOCATION;
    }

}
